// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn_ldFPTfRSxjpM35LZgspYzwo0pon1Z8',
    appId: '1:563488093355:web:dfcdf6291ef89667e7b3ee',
    messagingSenderId: '563488093355',
    projectId: 'credito-b5400',
    authDomain: 'credito-b5400.firebaseapp.com',
    storageBucket: 'credito-b5400.firebasestorage.app',
    measurementId: 'G-MGLS1X3Y5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHjYy2Y8tOjYfpRsS7QoE6xHrB-whRqoY',
    appId: '1:563488093355:android:7cdab56be0789b14e7b3ee',
    messagingSenderId: '563488093355',
    projectId: 'credito-b5400',
    storageBucket: 'credito-b5400.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaGLQvnjuIQyPT88jeFFhKARTtMcSMJPk',
    appId: '1:563488093355:ios:9161074b7c316920e7b3ee',
    messagingSenderId: '563488093355',
    projectId: 'credito-b5400',
    storageBucket: 'credito-b5400.firebasestorage.app',
    iosBundleId: 'com.credito.creditoApp',
  );
}
